[2025-07-29T22:16:34.824+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: table_dag.submit_tablea scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-07-29T22:16:34.837+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: table_dag.submit_tablea scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-07-29T22:16:34.839+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-07-29T22:16:34.853+0000] {taskinstance.py:1380} INFO - Executing <Task(PinotTableSubmitOperator): submit_tablea> on 2025-04-05 00:00:00+00:00
[2025-07-29T22:16:34.858+0000] {standard_task_runner.py:57} INFO - Started process 1278 to run task
[2025-07-29T22:16:34.861+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'table_dag', 'submit_tablea', 'scheduled__2025-04-05T00:00:00+00:00', '--job-id', '757', '--raw', '--subdir', 'DAGS_FOLDER/table_dag.py', '--cfg-path', '/tmp/tmpr0thb_m5']
[2025-07-29T22:16:34.863+0000] {standard_task_runner.py:85} INFO - Job 757: Subtask submit_tablea
[2025-07-29T22:16:34.899+0000] {task_command.py:415} INFO - Running <TaskInstance: table_dag.submit_tablea scheduled__2025-04-05T00:00:00+00:00 [running]> on host 931bde20eb1e
[2025-07-29T22:16:34.980+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='GGCODE' AIRFLOW_CTX_DAG_ID='table_dag' AIRFLOW_CTX_TASK_ID='submit_tablea' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T00:00:00+00:00'
[2025-07-29T22:16:34.992+0000] {pinot_table_operator.py:28} ERROR - Pinot table failed to submit to Apache Pinot! 409 - {"code":409,"error":"Table config for account_dim_OFFLINE already exists. If this is unexpected, try deleting the table to remove all metadata associated with it."}
[2025-07-29T22:16:34.996+0000] {pinot_table_operator.py:32} ERROR - An error occured: Table submission failed with status code 409
[2025-07-29T22:16:35.011+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=table_dag, task_id=submit_tablea, execution_date=20250405T000000, start_date=20250729T221634, end_date=20250729T221635
[2025-07-29T22:16:35.041+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-29T22:16:35.058+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
