[2025-07-31T21:54:47.106+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dimension_batch_ingestion.ingest_account_dim manual__2025-07-31T21:54:45.943708+00:00 [queued]>
[2025-07-31T21:54:47.124+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dimension_batch_ingestion.ingest_account_dim manual__2025-07-31T21:54:45.943708+00:00 [queued]>
[2025-07-31T21:54:47.127+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-07-31T21:54:47.165+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): ingest_account_dim> on 2025-07-31 21:54:45.943708+00:00
[2025-07-31T21:54:47.176+0000] {standard_task_runner.py:57} INFO - Started process 2330 to run task
[2025-07-31T21:54:47.186+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dimension_batch_ingestion', 'ingest_account_dim', 'manual__2025-07-31T21:54:45.943708+00:00', '--job-id', '1000', '--raw', '--subdir', 'DAGS_FOLDER/loader_dag.py', '--cfg-path', '/tmp/tmpqx1sjohn']
[2025-07-31T21:54:47.195+0000] {standard_task_runner.py:85} INFO - Job 1000: Subtask ingest_account_dim
[2025-07-31T21:54:47.310+0000] {task_command.py:415} INFO - Running <TaskInstance: dimension_batch_ingestion.ingest_account_dim manual__2025-07-31T21:54:45.943708+00:00 [running]> on host d47ad9177d65
[2025-07-31T21:54:47.450+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='GGCODE' AIRFLOW_CTX_DAG_ID='dimension_batch_ingestion' AIRFLOW_CTX_TASK_ID='ingest_account_dim' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T21:54:45.943708+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-31T21:54:45.943708+00:00'
[2025-07-31T21:54:47.451+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-31T21:54:47.452+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -X POST -F file=@/opt/***/account_dim_large_data.csv -H "Content-Type: multipart/form-data" "http://pinot-controller:9000/ingestFromFile?tableNameWithType=account_dim_OFFLINE&batchConfigMapStr=%7B%22inputFormat%22%3A%22csv%22%2C%22recordReader.prop.delimiter%22%3A%22%2C%22%7D"']
[2025-07-31T21:54:47.465+0000] {subprocess.py:86} INFO - Output:
[2025-07-31T21:54:47.496+0000] {subprocess.py:93} INFO - curl: (26) Failed to open/read local data from file/application
[2025-07-31T21:54:47.498+0000] {subprocess.py:97} INFO - Command exited with return code 26
[2025-07-31T21:54:47.520+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 26.
[2025-07-31T21:54:47.527+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dimension_batch_ingestion, task_id=ingest_account_dim, execution_date=20250731T215445, start_date=20250731T215447, end_date=20250731T215447
[2025-07-31T21:54:47.544+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1000 for task ingest_account_dim (Bash command failed. The command returned a non-zero exit code 26.; 2330)
[2025-07-31T21:54:47.580+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-31T21:54:47.630+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
