[2025-07-30T16:44:05.601+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dimension_batch_ingestion.ingest_branch_dim scheduled__2025-07-29T00:00:00+00:00 [queued]>
[2025-07-30T16:44:05.605+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dimension_batch_ingestion.ingest_branch_dim scheduled__2025-07-29T00:00:00+00:00 [queued]>
[2025-07-30T16:44:05.606+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-07-30T16:44:05.615+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): ingest_branch_dim> on 2025-07-29 00:00:00+00:00
[2025-07-30T16:44:05.617+0000] {standard_task_runner.py:57} INFO - Started process 240 to run task
[2025-07-30T16:44:05.620+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dimension_batch_ingestion', 'ingest_branch_dim', 'scheduled__2025-07-29T00:00:00+00:00', '--job-id', '917', '--raw', '--subdir', 'DAGS_FOLDER/loader_dag.py', '--cfg-path', '/tmp/tmpksp6yhnt']
[2025-07-30T16:44:05.623+0000] {standard_task_runner.py:85} INFO - Job 917: Subtask ingest_branch_dim
[2025-07-30T16:44:05.659+0000] {task_command.py:415} INFO - Running <TaskInstance: dimension_batch_ingestion.ingest_branch_dim scheduled__2025-07-29T00:00:00+00:00 [running]> on host 9f2ad20acb51
[2025-07-30T16:44:05.722+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='GGCODE' AIRFLOW_CTX_DAG_ID='dimension_batch_ingestion' AIRFLOW_CTX_TASK_ID='ingest_branch_dim' AIRFLOW_CTX_EXECUTION_DATE='2025-07-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-29T00:00:00+00:00'
[2025-07-30T16:44:05.723+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-30T16:44:05.724+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -X POST -F file=@/opt/***/branch_dim_large_data.csv -H "Content-Type: multipart/form-data" "http://pinot-controller:9000/ingestFromFile?tableNameWithType=branch_dim_OFFLINE&batchConfigMapStr=%7B%22inputFormat%22%3A%22csv%22%2C%22recordReader.prop.delimiter%22%3A%22%2C%22%7D"']
[2025-07-30T16:44:05.728+0000] {subprocess.py:86} INFO - Output:
[2025-07-30T16:44:05.732+0000] {subprocess.py:93} INFO - curl: (26) Failed to open/read local data from file/application
[2025-07-30T16:44:05.732+0000] {subprocess.py:97} INFO - Command exited with return code 26
[2025-07-30T16:44:05.739+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 26.
[2025-07-30T16:44:05.743+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dimension_batch_ingestion, task_id=ingest_branch_dim, execution_date=20250729T000000, start_date=20250730T164405, end_date=20250730T164405
[2025-07-30T16:44:05.751+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 917 for task ingest_branch_dim (Bash command failed. The command returned a non-zero exit code 26.; 240)
[2025-07-30T16:44:05.760+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-30T16:44:05.769+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
