[2025-07-28T22:52:12.986+0000] {processor.py:157} INFO - Started process (PID=958) to work on /opt/airflow/dags/schema_dag.py
[2025-07-28T22:52:12.987+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2025-07-28T22:52:12.988+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:52:12.988+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:52:13.250+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:52:13.260+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.278 seconds
[2025-07-28T22:52:20.379+0000] {processor.py:157} INFO - Started process (PID=987) to work on /opt/airflow/dags/schema_dag.py
[2025-07-28T22:52:20.379+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2025-07-28T22:52:20.380+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:52:20.380+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:52:20.383+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:52:20.382+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 19
    )
    ^
SyntaxError: invalid syntax
[2025-07-28T22:52:20.383+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:52:20.396+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.021 seconds
[2025-07-28T22:52:26.425+0000] {processor.py:157} INFO - Started process (PID=992) to work on /opt/airflow/dags/schema_dag.py
[2025-07-28T22:52:26.426+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2025-07-28T22:52:26.426+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:52:26.426+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:52:26.430+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:52:26.429+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 19
    )
    ^
SyntaxError: invalid syntax
[2025-07-28T22:52:26.430+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:52:26.440+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.020 seconds
[2025-07-28T22:52:56.913+0000] {processor.py:157} INFO - Started process (PID=1027) to work on /opt/airflow/dags/schema_dag.py
[2025-07-28T22:52:56.916+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2025-07-28T22:52:56.917+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:52:56.917+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:52:56.923+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:52:56.921+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 19
    )
    ^
SyntaxError: invalid syntax
[2025-07-28T22:52:56.924+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:52:56.948+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.046 seconds
[2025-07-28T22:53:27.541+0000] {processor.py:157} INFO - Started process (PID=1062) to work on /opt/airflow/dags/schema_dag.py
[2025-07-28T22:53:27.542+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2025-07-28T22:53:27.543+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:53:27.543+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:53:27.547+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:53:27.547+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 19
    )
    ^
SyntaxError: invalid syntax
[2025-07-28T22:53:27.548+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:53:27.562+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.025 seconds
[2025-07-28T22:53:58.069+0000] {processor.py:157} INFO - Started process (PID=1097) to work on /opt/airflow/dags/schema_dag.py
[2025-07-28T22:53:58.070+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2025-07-28T22:53:58.070+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:53:58.070+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:53:58.075+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:53:58.074+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 19
    )
    ^
SyntaxError: invalid syntax
[2025-07-28T22:53:58.075+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:53:58.092+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.026 seconds
[2025-07-28T22:54:15.233+0000] {processor.py:157} INFO - Started process (PID=1109) to work on /opt/airflow/dags/schema_dag.py
[2025-07-28T22:54:15.233+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2025-07-28T22:54:15.234+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:54:15.234+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:54:15.237+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:54:15.237+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 28
    )
    ^
SyntaxError: invalid syntax
[2025-07-28T22:54:15.238+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:54:15.259+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.030 seconds
[2025-07-28T22:54:29.687+0000] {processor.py:157} INFO - Started process (PID=1137) to work on /opt/airflow/dags/schema_dag.py
[2025-07-28T22:54:29.689+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2025-07-28T22:54:29.690+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:54:29.690+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:54:29.937+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:54:29.936+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 25, in <module>
    submit_schema = PinotSchemaSubmitOperator(
NameError: name 'PinotSchemaSubmitOperator' is not defined
[2025-07-28T22:54:29.937+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:54:29.955+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.279 seconds
[2025-07-28T22:54:37.812+0000] {processor.py:157} INFO - Started process (PID=1143) to work on /opt/airflow/dags/schema_dag.py
[2025-07-28T22:54:37.812+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2025-07-28T22:54:37.813+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:54:37.813+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:54:37.931+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:54:37.931+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 25, in <module>
    submit_schema = PinotSchemaSubmitOperator(
NameError: name 'PinotSchemaSubmitOperator' is not defined
[2025-07-28T22:54:37.932+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:54:37.939+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.130 seconds
[2025-07-28T22:55:08.427+0000] {processor.py:157} INFO - Started process (PID=1179) to work on /opt/airflow/dags/schema_dag.py
[2025-07-28T22:55:08.428+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2025-07-28T22:55:08.429+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:55:08.429+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:55:08.694+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:55:08.693+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 25, in <module>
    submit_schema = PinotSchemaSubmitOperator(
NameError: name 'PinotSchemaSubmitOperator' is not defined
[2025-07-28T22:55:08.694+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:55:08.707+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.284 seconds
[2025-07-28T22:55:23.907+0000] {processor.py:157} INFO - Started process (PID=1215) to work on /opt/airflow/dags/schema_dag.py
[2025-07-28T22:55:23.908+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2025-07-28T22:55:23.909+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:55:23.909+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:55:24.075+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:55:24.075+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 25, in <module>
    submit_schema = PinotSchemaSubmitOperator(
NameError: name 'PinotSchemaSubmitOperator' is not defined
[2025-07-28T22:55:24.075+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:55:24.082+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.178 seconds
[2025-07-28T22:55:51.458+0000] {processor.py:157} INFO - Started process (PID=1251) to work on /opt/airflow/dags/schema_dag.py
[2025-07-28T22:55:51.459+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2025-07-28T22:55:51.460+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:55:51.460+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:55:51.464+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:55:51.463+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8
    from
       ^
SyntaxError: invalid syntax
[2025-07-28T22:55:51.464+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2025-07-28T22:55:51.478+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.024 seconds
